name: 'Get Coverage for Front-end'
on:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest

        permissions:
            # Required to checkout the code
            contents: read
            # Required to put a comment into the pull-request
            pull-requests: write

        steps:
            - uses: actions/checkout@v2
            - name: 'Install Node'
              uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
            - name: 'intsall depedencies'
              run: cd frontend && npm install
            - name: 'get coverage'
              run: cd frontend && npx vitest --coverage

            # - name: Upload Coverage Summary Artifacts
            #   uses: actions/upload-artifact@v2
            #   with:
            #       name: Coverage Summary
            #       path: ${{ github.workspace }}/frontend/coverage/coverage-summary.json
            #       retention-days: 1
            # - name: Upload Coverage Final Artifacts
            #   uses: actions/upload-artifact@v2
            #   with:
            #       name: Coverage Final
            #       path: ${{ github.workspace }}/frontend/coverage/coverage-final.json
            #       retention-days: 1

            - name: 'Report Coverage'
              if: always() # Also generate the report if tests are failing
              uses: davelosert/vitest-coverage-report-action@v1
              with:
                  json-summary-path: ${{ github.workspace }}/frontend/coverage/coverage-summary.json
                  json-final-path: ${{ github.workspace }}/frontend/coverage/coverage-final.json
                  vite-config-path: ${{ github.workspace }}/frontend/vite.config.ts
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  working-directory: ${{ github.workspace }}/frontend
